# Generated by Django 4.0.6 on 2022-08-03 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tag', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('add_post', 'Can add post'), ('change_post', 'Can change a posts'), ('delete_post', 'Can delete a posts'), ('view_post', 'Can view a particular posts'), ('list_posts', 'Can list all posts')),
                'default_permissions': (),
            },
        ),
    ]
