# Generated by Django 4.1 on 2022-08-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqQuest', models.CharField(max_length=255)),
                ('faqAnswer', models.TextField()),
            ],
        ),
    ]
