# Generated by Django 4.1 on 2022-08-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=models.SlugField(default='faqs', max_length=255),
        ),
    ]
