# Generated by Django 4.0.6 on 2022-08-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
