<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-08-03 13:46
=======
# Generated by Django 4.1 on 2022-08-04 11:50
>>>>>>> main

import apps.file_control.filechecker
import apps.file_control.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', apps.file_control.filechecker.ContentTypeRestrictedFileField(upload_to=apps.file_control.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
<<<<<<< HEAD
            options={
                'permissions': (('add_file_upload', 'Can upload file'), ('change_file_upload', 'Can change the database of uploaded file'), ('delete_file_upload', 'Can delete uploaded file'), ('view_file_upload', 'Can view uploaded file'), ('list_file_upload', 'Can list all uploaded file')),
                'default_permissions': (),
            },
=======
>>>>>>> main
        ),
    ]
