<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.14 on 2022-08-04 00:39

=======
# Generated by Django 4.1 on 2022-08-04 11:50
=======
# Generated by Django 4.0.6 on 2022-08-05 05:07
>>>>>>> 03cfc020ac4957cf993bd3b245054da035351c5b

import apps.file_control.filechecker
import apps.file_control.models
>>>>>>> ca1c03bb8e5d14a2f9388d4743d401cb5dad44a3
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='file_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='file_control/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', apps.file_control.filechecker.ContentTypeRestrictedFileField(upload_to=apps.file_control.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> ca1c03bb8e5d14a2f9388d4743d401cb5dad44a3
            ],
            options={
                'permissions': (('add_file_upload', 'Can upload file'), ('change_file_upload', 'Can change the database of uploaded file'), ('delete_file_upload', 'Can delete uploaded file'), ('view_file_upload', 'Can view uploaded file'), ('list_file_upload', 'Can list all uploaded file')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MetaExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_file_url', models.URLField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='file_control.fileupload')),
            ],
        ),
    ]
