# Generated by Django 4.1 on 2022-08-07 13:24

import apps.file_control.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_file', models.FileField(upload_to=apps.file_control.models.user_directory_path)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fileupload',
            options={},
        ),
        migrations.DeleteModel(
            name='MetaExtract',
        ),
        migrations.AddField(
            model_name='metadata',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='file_control.fileupload'),
        ),
    ]
