# Generated by Django 4.1 on 2022-08-10 18:49

import apps.file_control.filechecker
import apps.file_control.models
import apps.file_control.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=apps.file_control.filechecker.ContentTypeRestrictedFileField(storage=apps.file_control.storage.OverwriteStorage(), upload_to=apps.file_control.models.user_directory_path),
        ),
    ]
