# Generated by Django 4.1 on 2022-08-16 12:05

import apps.file_control.filechecker
import apps.file_control.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_control', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=apps.file_control.filechecker.ContentTypeRestrictedFileField(upload_to=apps.file_control.models.user_directory_path),
        ),
    ]
